### ISSUE TITLE
DOI search below numbers on wall

### ISSUE THREAD

**Issue by erkannt** [freeyourscience/freeyourscience#10]
- [x] dummy endpoints for author and paper search as well as landing page
- [x] integration of 3rd party APIs to fill author and paper search endpoint with life
- [x] decide what information to show (e.g. only report results for papers that likely could be oa at no cost (removes visibility of false negatives); would then be a conservative estimate
- [x] layout human readable author page

**Comment by LGro** [comment]
Should the API dependencies for the author search continue to be that slow, we might want to go for a separate JS frontend and allow for a loading indicator to improve the UX.

**Comment by LGro** [comment]
Consider inquiring with the S2 API team about adding the DOI to the `author[papers]` response schema.
