### ISSUE TITLE
Clarify landing page

### ISSUE THREAD

**Issue by LGro** [freeyourscience/freeyourscience#19]
- ~1-2 sentences mission statement~
- [x] alternative to "liberate" that is closer to the specific action
- [x] visualize three steps author process

## Refactoring/Styling Stuff

- [x] center numbering
- [ ] nicer prioritizing?
- [x] link to homepage from about
- [ ] footer at bottom?

**Comment by LGro** [comment]
Proposal
```
For Authors
1. Search publications by author name, ORCID or DOI
2. Identify publications without an Open Access version but where publisher allows OA repub
3. Grant Open Access by republish the paper according to the publisher policy
```

**Comment by LGro** [comment]
I could imagine having the three stages in the header at all times, like a nav bar.
The search form could move into the first box.
Then on the publications page, the first box could be greyed out / check marked and the second box is highlighted as the current active step.
For the third, we'd link people to the republication page that is adaptive to the paper they selected (e.g. show appropriate preprint servers that are allowed)
![image](https://user-images.githubusercontent.com/4706479/103150909-1d1d3380-4779-11eb-8745-592f573997de.png)

**Comment by erkannt** [comment]
Yes! I like the idea of having the journey as a persistent element. Feels like we might end up relegating the number on the wall to the blurbs below the search box.

So we'd display the journey on the landing page, grey out step one on the author/paper page, grey out step two on the paper specific how to page. Me likey.

Regarding the wording, I think if we set the user target as authors, we can can make the language more specific:

```
1. Find your paywalled publications (Paywalls make it harder for other researchers to use and cite your work)
2. Learn about Open Access pathways (Many publishers have policies that allow for no-cost re-publication)
3. Re-publish your work Open Access (Upload an additional version of your work to e.g. arXiv or your library in accordance with the publisher policy)
```

**Comment by LGro** [comment]
So far I haven't found a version of the number on the wall below the three steps / search box, but how about this (with proper fluffy spacing between the boxes, haven't managed to get the mobile friendly gutter correct; this is not committed, just a preview)
![image](https://user-images.githubusercontent.com/4706479/103248627-bd3aae80-496b-11eb-9438-f90dd8fe4afc.png)

And very rough, what do we do about the author page. Leave the search for easy "search someone else without going back" or remove the search to keep more focus on step 2. Maybe also just grey out 1 and not 3, since it's still to come.
![image](https://user-images.githubusercontent.com/4706479/103248679-f8d57880-496b-11eb-9048-3194797944f6.png)
