### ISSUE TITLE
Remove GCP uptime check and scale to 1 instead

### ISSUE THREAD

**Issue by LGro** [freeyourscience/freeyourscience#41]
- [x] remove gcp uptime check
- [x] set prod scale to 1

**Comment by LGro** [comment]
Removed uptime checks.
TODO: Scale prod to 1 once we go live.

**Comment by erkannt** [comment]
removed in IaC: https://github.com/freeyourscience/infrastructure/commit/ffe62ca70320193a342061443b59818b9e329585
